# Generated by Django 5.2.5 on 2025-11-01 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'course_types',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('software_covered', models.TextField(blank=True)),
                ('duration_months', models.CharField(choices=[('6_weeks', '6 Weeks'), ('1_month', '1 Month'), ('2_months', '2 Months'), ('3_months', '3 Months'), ('4_months', '4 Months'), ('5_months', '5 Months'), ('6_months', '6 Months'), ('7_months', '7 Months'), ('8_months', '8 Months'), ('9_months', '9 Months'), ('10_months', '10 Months'), ('1_year', '1 Year')], max_length=20)),
                ('duration_hours', models.IntegerField(help_text='Total course hours')),
                ('course_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='staff_app.coursetype')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['course_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('trainer', 'Trainer'), ('counselor', 'counselor'), ('manager', 'Manager')], default='support', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'db_table': 'staff_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('qualification', models.CharField(max_length=100)),
                ('work_college', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('enquiry_date', models.DateField(auto_now_add=True)),
                ('centre', models.CharField(choices=[('jalandhar1', 'Jalandhar 1'), ('jalandhar2', 'Jalandhar 2'), ('maqsudan', 'Maqsudan'), ('ludhiana', 'Ludhiana'), ('hoshiarpur', 'Hoshiarpur'), ('mohali', 'Mohali'), ('phagwara', 'Phagwara')], max_length=20)),
                ('batch_time', models.CharField(blank=True, max_length=50)),
                ('course_fee_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('course_interested', models.CharField(blank=True, max_length=100)),
                ('trade', models.CharField(choices=[('computer', 'Computer'), ('it', 'IT'), ('graphic_designing', 'Graphic Designing'), ('civil', 'Civil'), ('mechanical', 'Mechanical'), ('ielts', 'IELTS'), ('ece', 'ECE'), ('programming', 'Programming'), ('digital_marketing', 'Digital Marketing'), ('hardware', 'Hardware'), ('networking', 'Networking')], max_length=20)),
                ('enquiry_source', models.CharField(choices=[('social_media', 'Social Media'), ('just_dial', 'Just Dial'), ('random_call', 'Random Call'), ('direct_visit', 'Direct Visit'), ('banner', 'Banner'), ('website', 'Website'), ('reference', 'Reference'), ('newspaper', 'Newspaper'), ('friend_reference', 'Friend Reference'), ('google_search', 'Google Search')], max_length=20)),
                ('enquiry_status', models.CharField(choices=[('registration_done', 'Registration Done'), ('visited', 'Visited'), ('in_process', 'In Process'), ('negative', 'Negative'), ('positive', 'Positive'), ('follow_up_required', 'Follow Up Required'), ('admission_done', 'Admission Done'), ('course_completed', 'Course Completed'), ('dropped', 'Dropped')], default='new', max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assign_enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_enquiries', to='staff_app.staffprofile')),
                ('enquiry_taken_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries_taken', to='staff_app.staffprofile')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('branch', models.CharField(choices=[('jalandhar1', 'Jalandhar 1'), ('jalandhar2', 'Jalandhar 2'), ('maqsudan', 'Maqsudan'), ('ludhiana', 'Ludhiana'), ('hoshiarpur', 'Hoshiarpur'), ('mohali', 'Mohali'), ('phagwara', 'Phagwara')], max_length=20)),
                ('joining_date', models.DateField()),
                ('student_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('qualification', models.CharField(max_length=100)),
                ('work_college', models.CharField(max_length=100)),
                ('contact_address', models.TextField()),
                ('phone_no', models.CharField(max_length=15)),
                ('whatsapp_no', models.CharField(blank=True, max_length=15)),
                ('parents_no', models.CharField(blank=True, max_length=15)),
                ('software_covered', models.TextField(blank=True)),
                ('duration_months', models.CharField(choices=[('6_weeks', '6 Weeks'), ('1_month', '1 Month'), ('2_months', '2 Months'), ('3_months', '3 Months'), ('4_months', '4 Months'), ('5_months', '5 Months'), ('6_months', '6 Months'), ('7_months', '7 Months'), ('8_months', '8 Months'), ('9_months', '9 Months'), ('10_months', '10 Months'), ('1_year', '1 Year')], max_length=20)),
                ('duration_hours', models.IntegerField()),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_course_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('course_completion_date', models.DateField(blank=True, null=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('certificate_issue_date', models.DateField(blank=True, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='staff_app.course')),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='staff_app.coursetype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registrations', to='staff_app.staffprofile')),
            ],
            options={
                'db_table': 'student_registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(help_text='Installment number (1st, 2nd, 3rd, etc.)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('cheque', 'Cheque'), ('card', 'Card'), ('upi', 'UPI')], default='cash', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID for online payments', max_length=100)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_payments', to='staff_app.staffprofile')),
                ('student_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='staff_app.studentregistration')),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['installment_number'],
            },
        ),
    ]
