# Generated by Django 4.2.25 on 2025-11-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0008_paymenttransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_api',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student Enquiry', 'verbose_name_plural': 'Student Enquiries'},
        ),
        migrations.RemoveField(
            model_name='student_api',
            name='work_college',
        ),
        migrations.AddField(
            model_name='student_api',
            name='class_name',
            field=models.CharField(blank=True, help_text="Required if student_type is 'school'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_api',
            name='college_name',
            field=models.CharField(blank=True, help_text="Required if student_type is 'college'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student_api',
            name='company_name',
            field=models.CharField(blank=True, help_text="Required if student_type is 'working'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student_api',
            name='job_role',
            field=models.CharField(blank=True, help_text="Required if student_type is 'working'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student_api',
            name='school_name',
            field=models.CharField(blank=True, help_text="Required if student_type is 'school'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student_api',
            name='semester',
            field=models.CharField(blank=True, help_text="Required if student_type is 'college'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_api',
            name='student_type',
            field=models.CharField(choices=[('college', 'College Student'), ('school', 'School Student'), ('working', 'Working Professional')], default=1, help_text='Type of student: college, school, or working', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_api',
            name='enquiry_status',
            field=models.CharField(choices=[('registration_done', 'Registration Done'), ('visited', 'Visited'), ('in_process', 'In Process'), ('negative', 'Negative'), ('positive', 'Positive'), ('follow_up_required', 'Follow Up Required'), ('admission_done', 'Admission Done'), ('course_completed', 'Course Completed'), ('dropped', 'Dropped')], default='in_process', max_length=20),
        ),
    ]
