# Generated by Django 4.2.25 on 2025-11-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0009_alter_student_api_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_api',
            name='class_mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('both', 'Both (Online & Offline)')], default=1, help_text='Preferred mode of class: online, offline, or both', max_length=10),
            preserve_default=False,
        ),
    ]
