# Generated by Django 4.2.25 on 2025-12-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0010_student_api_class_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='class_mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('both', 'Both (Online & Offline)')], default=1, help_text='Preferred mode of class: online, offline, or both', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='class_name',
            field=models.CharField(blank=True, help_text="Required if student_type is 'school'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='college_name',
            field=models.CharField(blank=True, help_text="Required if student_type is 'college'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='company_name',
            field=models.CharField(blank=True, help_text="Required if student_type is 'working'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='job_role',
            field=models.CharField(blank=True, help_text="Required if student_type is 'working'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='school_name',
            field=models.CharField(blank=True, help_text="Required if student_type is 'school'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='semester',
            field=models.CharField(blank=True, help_text="Required if student_type is 'college'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='student_type',
            field=models.CharField(choices=[('college', 'College Student'), ('school', 'School Student'), ('working', 'Working Professional')], default=1, help_text='Type of student: college, school, or working', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='work_college',
            field=models.CharField(help_text='Current workplace or college name', max_length=200),
        ),
    ]
