# Generated by Django 4.2 on 2025-12-27 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_app', '0011_studentregistration_class_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('jalandhar1', 'Jalandhar 1'), ('jalandhar2', 'Jalandhar 2'), ('maqsudan', 'Maqsudan'), ('ludhiana', 'Ludhiana'), ('hoshiarpur', 'Hoshiarpur'), ('mohali', 'Mohali'), ('phagwara', 'Phagwara')], max_length=20, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branch_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Branch Profile',
                'verbose_name_plural': 'Branch Profiles',
                'db_table': 'branch_profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
