# Generated by Django 4.2 on 2025-12-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0012_branchprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_api',
            name='converted_to_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student_api',
            name='registration_id',
            field=models.IntegerField(blank=True, help_text='ID of created registration', null=True),
        ),
    ]
